INSERT INTO machine (id, machine, location) VALUES (1, 'Climatisation', 'Lyon');
INSERT INTO machine (id, machine, location) VALUES (2, 'Compresseur', 'Marseille');
INSERT INTO machine (id, machine, location) VALUES (3, 'Pompe Hydraulique', 'Paris');
INSERT INTO machine (id, machine, location) VALUES (4, 'Generatrice', 'Toulouse');
INSERT INTO machine (id, machine, location) VALUES (5, 'Turbine', 'Nice');
INSERT INTO machine (id, machine, location) VALUES (6, 'Chaudiere', 'Bordeaux');
INSERT INTO machine (id, machine, location) VALUES (7, 'Ventilateur', 'Nantes');
INSERT INTO machine (id, machine, location) VALUES (8, 'Convoyeur', 'Strasbourg');
INSERT INTO machine (id, machine, location) VALUES (9, 'Moteur Diesel', 'Lille');
INSERT INTO machine (id, machine, location) VALUES (10, 'Pompe a vide', 'Grenoble');
INSERT INTO machine (id, machine, location) VALUES (11, 'Press hydraulique', 'Lyon');
INSERT INTO machine (id, machine, location) VALUES (12, 'Broyeuse', 'Marseille');
INSERT INTO machine (id, machine, location) VALUES (13, 'Melangeur', 'Paris');
INSERT INTO machine (id, machine, location) VALUES (14, 'Four industriel', 'Toulouse');
INSERT INTO machine (id, machine, location) VALUES (15, 'Robot de soudure', 'Nice');
INSERT INTO machine (id, machine, location) VALUES (16, 'Machine CNC', 'Bordeaux');
INSERT INTO machine (id, machine, location) VALUES (17, 'Laminoir', 'Nantes');
INSERT INTO machine (id, machine, location) VALUES (18, 'Presse plieuse', 'Strasbourg');
INSERT INTO machine (id, machine, location) VALUES (19, 'Scie automatique', 'Lille');
INSERT INTO machine (id, machine, location) VALUES (20, 'Tour numerique', 'Grenoble');
INSERT INTO machine (id, machine, location) VALUES (21, 'Imprimante 3D', 'Lyon');
INSERT INTO machine (id, machine, location) VALUES (22, 'Fraiseuse', 'Marseille');
INSERT INTO machine (id, machine, location) VALUES (23, 'Rectifieuse', 'Paris');
INSERT INTO machine (id, machine, location) VALUES (24, 'Pompe à eau', 'Toulouse');
INSERT INTO machine (id, machine, location) VALUES (25, 'Pompe centrifuge', 'Nice');
INSERT INTO machine (id, machine, location) VALUES (26, 'Compresseur d’air', 'Bordeaux');
INSERT INTO machine (id, machine, location) VALUES (27, 'Système de refroidissement', 'Nantes');
INSERT INTO machine (id, machine, location) VALUES (28, 'Filtre à huile', 'Strasbourg');
INSERT INTO machine (id, machine, location) VALUES (29, 'Secheur', 'Lille');
INSERT INTO machine (id, machine, location) VALUES (30, 'Extracteur', 'Grenoble');
INSERT INTO machine (id, machine, location) VALUES (31, 'Eaporateur', 'Lyon');
INSERT INTO machine (id, machine, location) VALUES (32, 'Machine d’emballage', 'Marseille');
INSERT INTO machine (id, machine, location) VALUES (33, 'Etiqueteuse', 'Paris');
INSERT INTO machine (id, machine, location) VALUES (34, 'Doseuse', 'Toulouse');
INSERT INTO machine (id, machine, location) VALUES (35, 'Melangeur chimique', 'Nice');
INSERT INTO machine (id, machine, location) VALUES (36, 'Distributeur automatique', 'Bordeaux');
INSERT INTO machine (id, machine, location) VALUES (37, 'Cuve de melange', 'Nantes');
INSERT INTO machine (id, machine, location) VALUES (38, 'Machine a polir', 'Strasbourg');
INSERT INTO machine (id, machine, location) VALUES (39, 'Robot de manutention', 'Lille');
INSERT INTO machine (id, machine, location) VALUES (40, 'Centrale hydraulique', 'Grenoble');
INSERT INTO machine (id, machine, location) VALUES (41, 'Chiller', 'Lyon');
INSERT INTO machine (id, machine, location) VALUES (42, 'Machine de decoupe laser', 'Marseille');
INSERT INTO machine (id, machine, location) VALUES (43, 'Unité de traitement d’air', 'Paris');
INSERT INTO machine (id, machine, location) VALUES (44, 'Machine a laver industrielle', 'Toulouse');
INSERT INTO machine (id, machine, location) VALUES (45, 'Refroidisseur', 'Nice');
INSERT INTO machine (id, machine, location) VALUES (46, 'Machine de conditionnement', 'Bordeaux');
INSERT INTO machine (id, machine, location) VALUES (47, 'Crible', 'Nantes');
INSERT INTO machine (id, machine, location) VALUES (48, 'Tremie', 'Strasbourg');
INSERT INTO machine (id, machine, location) VALUES (49, 'Pompe doseuse', 'Lille');
INSERT INTO machine (id, machine, location) VALUES (50, 'Extracteur de poussiere', 'Grenoble');